FROM ghcr.io/ublue-os/bazzite-nvidia:stable AS pwnlinux-nvidia

COPY system_files /
COPY scripts /scripts

RUN mkdir -p /var/lib/alternatives && \
/scripts/remove-packages.sh && \
/scripts/install-packages.sh && \
/scripts/remove-packages.sh && \
ostree container commit
