FROM ghcr.io/ublue-os/bazzite:stable AS pwnlinux

COPY system_files/desktop/kinoite /
COPY system_files/overrides /
COPY scripts /scripts

RUN mkdir -p /var/lib/alternatives && \
/scripts/remove-packages.sh && \
/scripts/install-packages.sh && \
/scripts/remove-files.sh && \
ostree container commit
