FROM ghcr.io/ublue-os/bazzite-nvidia:stable AS pwnlinux-nvidia

COPY system_files/desktop/kinoite /
OPY system_files/nvidia/kinoite /
COPY system_files/overrides /
COPY scripts /tmp/scripts

RUN mkdir -p /var/lib/alternatives && \
/tmp/scripts/remove-packages.sh && \
/tmp/scripts/install-packages.sh && \
/tmp/scripts/remove-files.sh && \
ostree container commit
