ARG BASE_IMAGE_NAME="${BASE_IMAGE_NAME:-kinoite}"
ARG BASE_IMAGE_FLAVOR="${BASE_IMAGE_FLAVOR:-main}"
ARG IMAGE_FLAVOR="${IMAGE_FLAVOR:-main}"
ARG KERNEL_FLAVOR="${KERNEL_FLAVOR:-fsync}"
ARG IMAGE_BRANCH="${IMAGE_BRANCH:-main}"
ARG SOURCE_IMAGE="${SOURCE_IMAGE:-$BASE_IMAGE_NAME-$BASE_IMAGE_FLAVOR}"
ARG BASE_IMAGE="ghcr.io/ublue-os/${SOURCE_IMAGE}"
ARG FEDORA_MAJOR_VERSION="${FEDORA_MAJOR_VERSION:-40}"

FROM ghcr.io/ublue-os/bazzite:stable AS pwnlinux-pa

ARG IMAGE_NAME="${IMAGE_NAME:-pwnlinux-pa}"
ARG IMAGE_VENDOR="${IMAGE_VENDOR:-pwn-linux}"
ARG IMAGE_FLAVOR="${IMAGE_FLAVOR:-main}"
ARG KERNEL_FLAVOR="${KERNEL_FLAVOR:-fsync}"
ARG IMAGE_BRANCH="${IMAGE_BRANCH:-main}"
ARG BASE_IMAGE_NAME="${BASE_IMAGE_NAME:-kinoite}"
ARG FEDORA_MAJOR_VERSION="${FEDORA_MAJOR_VERSION:-40}"

COPY system_files/desktop/kinoite /
COPY system_files/desktop/shared /
COPY system_files/overrides /
COPY scripts/kinoite /scripts

RUN /scripts/prepare.sh && \
    /scripts/remove-packages.sh && \
    /scripts/remove-pipewire.sh && \
    /scripts/install-packages.sh && \
    /scripts/finalize.sh && \
    ostree container commit

FROM ghcr.io/ublue-os/bazzite-nvidia:stable AS pwnlinux-nvidia-pa

ARG IMAGE_NAME="${IMAGE_NAME:-pwnlinux-nvidia-pa}"
ARG IMAGE_VENDOR="${IMAGE_VENDOR:-pwn-linux}"
ARG IMAGE_FLAVOR="${IMAGE_FLAVOR:-nvidia}"
ARG KERNEL_FLAVOR="${KERNEL_FLAVOR:-fsync}"
ARG IMAGE_BRANCH="${IMAGE_BRANCH:-main}"
ARG BASE_IMAGE_NAME="${BASE_IMAGE_NAME:-kinoite}"
ARG FEDORA_MAJOR_VERSION="${FEDORA_MAJOR_VERSION:-40}"

COPY system_files/desktop/kinoite /
COPY system_files/desktop/shared /
COPY system_files/nvidia/kinoite /
COPY system_files/overrides /
COPY scripts/kinoite /scripts

RUN /scripts/prepare.sh && \
    /scripts/remove-packages.sh && \
    /scripts/remove-pipewire.sh && \
    /scripts/install-packages.sh && \
    /scripts/finalize.sh && \
    ostree container commit