FROM ghcr.io/ublue-os/bazzite:stable AS pwnlinux

COPY build.sh /tmp/build.sh

RUN mkdir -p /var/lib/alternatives && \
    rpm-ostree override remove pipewire-pulseaudio --install pulseaudio && \
    ostree container commit && \
    rpm-ostree override remove \
    ptyxis \
    input-remapper \
    kde-connect-libs \
    kdeconnectd \
    kde-connect \
    kcharselect \
    krfb \
    krfb-libs \
    kmousetool \
    rom-properties-kf6 \
    qsynth && \
    rm /usr/share/applications/com.gerbilsoft.rom-properties.rp-config.desktop && \
    ostree container commit && \
    rpm-ostree install \
    konsole \
    rust \
    pamixer \
    playerctl \
    cargo && \
    ostree container commit
